use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

include!("app_commands.rs");

const APP_ICON_SVG: &[u8] = include_bytes!("../src/mework-icon.svg");
const APP_ICON_SMALL_SVG: &[u8] = include_bytes!("../src/mework-icon-small.svg");
const APP_ICON_SIZES: [u32; 6] = [16, 24, 32, 48, 128, 256];
/// The smallest frame the full desk scene is still drawn at.
///
/// `mework-icon.svg` is a scene — cat, desk, laptop, tail — and below roughly a
/// 64px frame its parts stop resolving into anything: the face collapses, the
/// laptop merges with the desk, and the result is a smudge with ears. The
/// Explorer/taskbar sizes therefore come from `mework-icon-small.svg`, which is
/// the same creature's head alone on the same plate. Both are inputs to this
/// build script, so both have to be registered in
/// `browserDevRustFingerprintEntries` and in the Pages workflow's path filter.
const APP_ICON_SCENE_MIN_SIZE: u32 = 64;

macro_rules! app_command_names {
    ($($command:ident),* $(,)?) => {
        &[$(stringify!($command)),*]
    };
}

const APP_COMMANDS: &[&str] = mework_app_commands!(app_command_names);

fn main() {
    prefer_mingw_toolchain();
    stage_aisdk_sidecar();
    stage_claude_code();
    println!("cargo:rerun-if-changed=../src/mework-icon.svg");
    println!("cargo:rerun-if-changed=../src/mework-icon-small.svg");
    let output_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let icon_path = output_dir.join("mework-icon.ico");
    let icon = generated_icon();
    fs::write(&icon_path, &icon).expect("write generated Windows icon");
    let manifest_icon =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"))
            .join("icons")
            .join("icon.ico");
    fs::create_dir_all(manifest_icon.parent().expect("icon parent"))
        .expect("create generated icon directory");
    if !matches!(fs::read(&manifest_icon), Ok(existing) if existing == icon) {
        fs::write(&manifest_icon, &icon).expect("write generated application icon");
    }

    let windows = if embed_windows_manifest_for_all_link_targets(&output_dir) {
        // The Windows manifest is already linked into every executable (bins and every
        // cargo test harness) above. tauri-build only covers bins, and adding its copy on
        // top would link a second RT_MANIFEST resource into them.
        tauri_build::WindowsAttributes::new_without_app_manifest()
    } else {
        // Keep the same explicit asInvoker/uiAccess=false boundary on MSVC and
        // any future Windows linker path instead of relying on tauri-build's
        // implicit default manifest.
        tauri_build::WindowsAttributes::new().app_manifest(include_str!("windows-app-manifest.xml"))
    }
    .window_icon_path(icon_path);
    let attributes = tauri_build::Attributes::new()
        .windows_attributes(windows)
        .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
    tauri_build::try_build(attributes).expect("build Tauri application metadata");
    prune_retired_command_permissions();
}

/// Deletes the generated permission files of commands that no longer exist.
///
/// `tauri_build::try_build` writes one `permissions/autogenerated/<command>.toml` per entry
/// of `APP_COMMANDS`, but it only ever *adds*: retiring a command leaves its file behind
/// forever. The directory is gitignored build output, so the residue is invisible to review
/// and survives every rebuild — the ACL then advertises `allow-<retired-command>` identifiers
/// that no command and no capability back.
///
/// Only files this build script's own generator could have written are considered: a
/// `<stem>.toml` directly in the directory, carrying tauri-build's header, whose stem is not
/// a live command. Anything else is left alone.
fn prune_retired_command_permissions() {
    let directory = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"))
        .join("permissions")
        .join("autogenerated");
    let Ok(entries) = fs::read_dir(&directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("toml") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        if APP_COMMANDS.contains(&stem) {
            continue;
        }
        // A hand-written permission file that happens to sit here is not this script's to
        // delete; the header is what marks the file as generated.
        if !matches!(fs::read_to_string(&path), Ok(text) if text.starts_with("# Automatically generated"))
        {
            continue;
        }
        if fs::remove_file(&path).is_ok() {
            println!("cargo:warning=删除已退役命令的权限文件 {stem}.toml");
        }
    }
}

/// Stages the AI SDK sidecar where `externalBin` expects it.
///
/// `tauri.conf.json` declares `binaries/mework-aisdk`, and Tauri resolves that to
/// `binaries/mework-aisdk-<target-triple><exe>`. If the file is absent, *every* build fails —
/// `cargo check` and `cargo test` included — with a message that says nothing about how to fix
/// it. That is a bad first five minutes for a fresh clone, so this stages the artifact itself.
///
/// The triple comes from `TARGET`, which Cargo sets for the build script. That is the
/// authoritative value; deriving it a second time by parsing `rustc -vV` elsewhere would only
/// create a second thing that can drift. `scripts/build-aisdk-sidecar.mjs` therefore only
/// *builds* `aisdk-service/dist/`; naming and placement live here alone.
///
/// The copy is skipped when the staged file already matches the built one by size and mtime:
/// the sidecar is ~90 MiB and this runs on every build script invocation.
fn stage_aisdk_sidecar() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let repo = manifest.parent().expect("repository root").to_path_buf();
    let exe_suffix = if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        ".exe"
    } else {
        ""
    };
    let built = repo
        .join("aisdk-service")
        .join("dist")
        .join(format!("mework-aisdk{exe_suffix}"));
    println!("cargo:rerun-if-changed={}", built.display());

    let target = env::var("TARGET").expect("TARGET is set by Cargo for build scripts");
    // The crate needs the same triple at runtime to find the staged copy (the aisdk tests look
    // for exactly the file this function guarantees). Exporting it here keeps one owner for the
    // value instead of parsing `rustc -vV` a second time somewhere else.
    println!("cargo:rustc-env=MEWORK_TARGET_TRIPLE={target}");
    let staged = manifest
        .join("binaries")
        .join(format!("mework-aisdk-{target}{exe_suffix}"));
    println!("cargo:rerun-if-changed={}", staged.display());

    let built_meta = fs::metadata(&built).ok();
    let Some(built_meta) = built_meta else {
        // Nothing to stage from. An already-staged copy is fine — that is the packaging box,
        // where `beforeBuildCommand` produced it and `aisdk-service/` may not even be present.
        assert!(
            staged.is_file(),
            "AI SDK 侧车缺席，Tauri 的 externalBin 找不到 {}。\n\
             先跑 `npm run build:sidecar`（会在 aisdk-service/ 里打出单文件可执行），\n\
             或者在 aisdk-service/ 里跑 `npm run build:sea`。",
            staged.display(),
        );
        return;
    };

    if let Ok(staged_meta) = fs::metadata(&staged) {
        let same_size = staged_meta.len() == built_meta.len();
        let fresh = match (staged_meta.modified(), built_meta.modified()) {
            (Ok(staged_at), Ok(built_at)) => staged_at >= built_at,
            _ => false,
        };
        if same_size && fresh {
            return;
        }
    }

    fs::create_dir_all(staged.parent().expect("binaries directory"))
        .expect("create the sidecar staging directory");
    fs::copy(&built, &staged).expect("stage the AI SDK sidecar for externalBin");
}

/// The Claude Code build the `claude_agent` family runs, and the only one it will
/// run: this is the version Mework ships, not whatever the user happens to have
/// installed.
///
/// It is the CLI inside the Agent SDK's own platform package, so the SDK and the
/// executable it drives can never disagree — the npm pin in
/// `aisdk-service/package.json` is exact for that reason, and
/// [`stage_claude_code`] refuses to build if the installed SDK declares a
/// different `claudeCodeVersion`. Bumping the CLI therefore means bumping the SDK
/// pin and this constant together, then re-reading what changed in the CLI's own
/// behaviour (see `docs/model-providers.md`).
const CLAUDE_CODE_VERSION: &str = "2.1.261";

/// The Agent SDK's npm platform package for the build target, in the SDK's own
/// naming: `process.platform`-`process.arch`, plus `-musl` where the C library
/// decides which binary runs. The SDK resolves exactly this name when no
/// executable is handed to it, so mirroring it here ships the file the SDK itself
/// would have picked.
fn claude_code_platform_package() -> String {
    let os = env::var("CARGO_CFG_TARGET_OS").expect("CARGO_CFG_TARGET_OS is set for build scripts");
    let arch =
        env::var("CARGO_CFG_TARGET_ARCH").expect("CARGO_CFG_TARGET_ARCH is set for build scripts");
    let platform = match os.as_str() {
        "windows" => "win32",
        "macos" => "darwin",
        "linux" => "linux",
        other => panic!("Claude Code 没有 {other} 的平台包；该家族无法在此目标上发布"),
    };
    let arch = match arch.as_str() {
        "x86_64" => "x64",
        "aarch64" => "arm64",
        other => panic!("Claude Code 没有 {platform}-{other} 的平台包"),
    };
    // The musl and glibc builds are separate downloads: a glibc binary on a musl
    // host fails to launch because the loader it names is absent.
    let libc = if env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("musl") {
        "-musl"
    } else {
        ""
    };
    format!("@anthropic-ai/claude-agent-sdk-{platform}-{arch}{libc}")
}

/// Reads one string field out of a package manifest.
///
/// A whole JSON parser is not a build dependency here, and the input is npm's own
/// published `package.json` rather than user input: the field is found by key and
/// the answer is the next quoted string.
fn json_string_field(text: &str, key: &str) -> Option<String> {
    let after_key = text.split_once(&format!("\"{key}\""))?.1;
    let after_colon = after_key.split_once(':')?.1;
    let opened = after_colon.split_once('"')?.1;
    Some(opened.split_once('"')?.0.to_owned())
}

/// Stages the bundled Claude Code CLI where `externalBin` expects it.
///
/// `tauri.conf.json` declares `binaries/claude` next to `binaries/mework-aisdk`,
/// so the CLI lands beside the application executable and both the host (login
/// probe, interactive login) and the sidecar resolve it from there — see
/// `src-tauri/src/aisdk/agent.rs::bundled_executable`.
///
/// The source is the Agent SDK's platform package in `aisdk-service/node_modules`,
/// which npm installs as an optional dependency of the pinned SDK. An install that
/// skipped optional dependencies has no CLI to ship, and the resulting build would
/// fail every `claude_agent` request at runtime instead, so that is a build error
/// here.
///
/// The version gate is the point of the exercise: the declared `claudeCodeVersion`
/// must equal [`CLAUDE_CODE_VERSION`], and the value is exported to the crate so a
/// test can assert the same number the build shipped. A tree with no
/// `node_modules` at all keeps an already-staged copy rather than failing — the
/// release flow always has one (`beforeBuildCommand` needs it), and a stale staged
/// binary is caught at runtime by
/// `aisdk::agent::tests::the_bundled_executable_reports_the_pinned_claude_code_version`
/// and by the sidecar's `cc_version` assertion.
fn stage_claude_code() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let repo = manifest.parent().expect("repository root").to_path_buf();
    let exe_suffix = if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        ".exe"
    } else {
        ""
    };
    let modules = repo.join("aisdk-service").join("node_modules");
    let sdk_manifest = modules
        .join("@anthropic-ai")
        .join("claude-agent-sdk")
        .join("package.json");
    let source = modules
        .join(claude_code_platform_package())
        .join(format!("claude{exe_suffix}"));
    println!("cargo:rerun-if-changed={}", sdk_manifest.display());
    println!("cargo:rerun-if-changed={}", source.display());
    println!("cargo:rustc-env=MEWORK_CLAUDE_CODE_VERSION={CLAUDE_CODE_VERSION}");

    let target = env::var("TARGET").expect("TARGET is set by Cargo for build scripts");
    let staged = manifest
        .join("binaries")
        .join(format!("claude-{target}{exe_suffix}"));
    println!("cargo:rerun-if-changed={}", staged.display());

    // The SDK ships the CLI's version in its own manifest. Checking it before the
    // copy is what makes "Mework runs Claude Code 2.1.261" a fact about the build
    // rather than a hope about node_modules.
    if let Ok(text) = fs::read_to_string(&sdk_manifest) {
        let declared = json_string_field(&text, "claudeCodeVersion");
        assert!(
            declared.as_deref() == Some(CLAUDE_CODE_VERSION),
            "{} 声明的 Claude Code 版本是 {}，而 Mework 锁定的是 {CLAUDE_CODE_VERSION}。\n\
             两者必须一致：要么把 aisdk-service/package.json 的 @anthropic-ai/claude-agent-sdk \
             钉回捆绑 {CLAUDE_CODE_VERSION} 的那个版本，\n\
             要么连同 build.rs 的 CLAUDE_CODE_VERSION 一起升级，并复核 CLI 自身行为的变化。",
            sdk_manifest.display(),
            declared.unwrap_or_else(|| "（读不到）".to_owned()),
        );
    }

    let Some(source_meta) = fs::metadata(&source).ok() else {
        // Nothing to stage from. An already-staged copy is fine — that is the packaging box,
        // where `beforeBuildCommand` populated `aisdk-service/` before this ran.
        assert!(
            staged.is_file(),
            "Mework 要随包附带的 Claude Code 缺席，Tauri 的 externalBin 找不到 {}。\n\
             它来自 Agent SDK 的平台包 {}，\n\
             在 aisdk-service/ 里跑 `npm install`（不要带 --omit=optional）就会装上。",
            staged.display(),
            source.display(),
        );
        return;
    };

    if let Ok(staged_meta) = fs::metadata(&staged) {
        let same_size = staged_meta.len() == source_meta.len();
        let fresh = match (staged_meta.modified(), source_meta.modified()) {
            (Ok(staged_at), Ok(source_at)) => staged_at >= source_at,
            _ => false,
        };
        if same_size && fresh {
            return;
        }
    }

    fs::create_dir_all(staged.parent().expect("binaries directory"))
        .expect("create the sidecar staging directory");
    fs::copy(&source, &staged).expect("stage the bundled Claude Code for externalBin");
}

///
/// tauri-build (via tauri-winres/embed-resource) attaches the manifest with
/// `cargo:rustc-link-arg-bins`, which cargo test harnesses never receive. Without a manifest
/// declaring the Common-Controls v6 dependency, the loader resolves comctl32.dll to the legacy
/// v5 copy in System32, which lacks `TaskDialogIndirect` (imported through muda/rfd), and MSVC
/// test executables die at load with STATUS_ENTRYPOINT_NOT_FOUND. Linking the explicit manifest
/// everywhere also makes GNU ld drop MinGW's default manifest object, leaving each executable
/// with exactly one RT_MANIFEST.
fn embed_windows_manifest_for_all_link_targets(output_dir: &Path) -> bool {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return false;
    }
    let manifest_path = output_dir.join("mework-app.manifest");
    fs::write(&manifest_path, include_str!("windows-app-manifest.xml"))
        .expect("write Windows application manifest");
    let resource_path = output_dir.join("mework-manifest.rc");
    let resource_manifest_path = manifest_path.to_string_lossy().replace('\\', "/");
    fs::write(
        &resource_path,
        format!("1 24 \"{resource_manifest_path}\"\n"),
    )
    .expect("write Windows manifest resource script");

    match env::var("CARGO_CFG_TARGET_ENV").as_deref() {
        Ok("gnu") => {
            let object_name = "mework-manifest.o";
            let windres = ["windres", "x86_64-w64-mingw32-windres"]
                .into_iter()
                .find(|name| {
                    Command::new(name)
                        .arg("--version")
                        .output()
                        .is_ok_and(|output| output.status.success())
                })
                .expect("windres is required to embed the Windows manifest on windows-gnu");
            let status = Command::new(windres)
                .current_dir(output_dir)
                .args(["-O", "coff", "-i", "mework-manifest.rc", "-o", object_name])
                .status()
                .expect("run windres");
            assert!(status.success(), "windres failed with {status}");
            println!(
                "cargo:rustc-link-arg={}",
                output_dir.join(object_name).display()
            );
            true
        }
        Ok("msvc") => {
            embed_resource::compile_for_everything(&resource_path, embed_resource::NONE)
                .manifest_required()
                .expect("compile Windows application manifest for all MSVC targets");
            true
        }
        _ => false,
    }
}

fn prefer_mingw_toolchain() {
    #[cfg(all(windows, target_env = "gnu"))]
    {
        let Some(path) = env::var_os("PATH") else {
            return;
        };
        let entries = env::split_paths(&path).collect::<Vec<_>>();
        let Some(mingw_bin) = entries
            .iter()
            .find(|entry| {
                entry
                    .components()
                    .rev()
                    .take(2)
                    .map(|part| part.as_os_str().to_string_lossy().to_lowercase())
                    .collect::<Vec<_>>()
                    == ["bin", "mingw64"]
            })
            .cloned()
        else {
            return;
        };
        let reordered = std::iter::once(mingw_bin.clone())
            .chain(entries.into_iter().filter(|entry| entry != &mingw_bin))
            .collect::<Vec<_>>();
        if let Ok(path) = env::join_paths(reordered) {
            env::set_var("PATH", path);
        }
    }
}

fn generated_icon() -> Vec<u8> {
    let options = resvg::usvg::Options::default();
    let parse = |svg: &[u8], what: &str| {
        resvg::usvg::Tree::from_data(svg, &options).unwrap_or_else(|_| panic!("parse {what}"))
    };
    let scene = parse(APP_ICON_SVG, "the canonical Mework SVG icon");
    let head = parse(APP_ICON_SMALL_SVG, "the small-frame Mework SVG icon");
    let png_images = APP_ICON_SIZES
        .into_iter()
        .map(|size| {
            let tree = if size >= APP_ICON_SCENE_MIN_SIZE {
                &scene
            } else {
                &head
            };
            let mut pixmap =
                resvg::tiny_skia::Pixmap::new(size, size).expect("allocate Mework icon pixmap");
            let transform = resvg::tiny_skia::Transform::from_scale(
                size as f32 / tree.size().width(),
                size as f32 / tree.size().height(),
            );
            resvg::render(tree, transform, &mut pixmap.as_mut());
            pixmap.encode_png().expect("encode Mework icon PNG")
        })
        .collect::<Vec<_>>();

    let directory_bytes = 6 + png_images.len() * 16;
    let image_bytes = png_images.iter().map(Vec::len).sum::<usize>();
    let mut icon = Vec::with_capacity(directory_bytes + image_bytes);
    icon.extend_from_slice(&0_u16.to_le_bytes());
    icon.extend_from_slice(&1_u16.to_le_bytes());
    icon.extend_from_slice(&(png_images.len() as u16).to_le_bytes());

    let mut image_offset = directory_bytes as u32;
    for (size, png) in APP_ICON_SIZES.into_iter().zip(&png_images) {
        let directory_size = if size == 256 { 0 } else { size as u8 };
        icon.extend_from_slice(&[directory_size, directory_size, 0, 0]);
        icon.extend_from_slice(&1_u16.to_le_bytes());
        icon.extend_from_slice(&32_u16.to_le_bytes());
        icon.extend_from_slice(&(png.len() as u32).to_le_bytes());
        icon.extend_from_slice(&image_offset.to_le_bytes());
        image_offset += png.len() as u32;
    }
    for png in png_images {
        icon.extend_from_slice(&png);
    }
    icon
}
