use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

include!("app_commands.rs");

const APP_ICON_SVG: &[u8] = include_bytes!("../src/mework-icon.svg");
const APP_ICON_SIZES: [u32; 6] = [16, 24, 32, 48, 128, 256];

macro_rules! app_command_names {
    ($($command:ident),* $(,)?) => {
        &[$(stringify!($command)),*]
    };
}

const APP_COMMANDS: &[&str] = mework_app_commands!(app_command_names);

fn main() {
    prefer_mingw_toolchain();
    stage_aisdk_sidecar();
    println!("cargo:rerun-if-changed=../src/mework-icon.svg");
    let output_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let icon_path = output_dir.join("mework-icon.ico");
    let icon = generated_icon();
    fs::write(&icon_path, &icon).expect("write generated Windows icon");
    let manifest_icon =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"))
            .join("icons")
            .join("icon.ico");
    fs::create_dir_all(manifest_icon.parent().expect("icon parent"))
        .expect("create generated icon directory");
    if !matches!(fs::read(&manifest_icon), Ok(existing) if existing == icon) {
        fs::write(&manifest_icon, &icon).expect("write generated application icon");
    }

    let windows = if embed_windows_manifest_for_all_link_targets(&output_dir) {
        // The Windows manifest is already linked into every executable (bins and every
        // cargo test harness) above. tauri-build only covers bins, and adding its copy on
        // top would link a second RT_MANIFEST resource into them.
        tauri_build::WindowsAttributes::new_without_app_manifest()
    } else {
        // Keep the same explicit asInvoker/uiAccess=false boundary on MSVC and
        // any future Windows linker path instead of relying on tauri-build's
        // implicit default manifest.
        tauri_build::WindowsAttributes::new().app_manifest(include_str!("windows-app-manifest.xml"))
    }
    .window_icon_path(icon_path);
    let attributes = tauri_build::Attributes::new()
        .windows_attributes(windows)
        .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
    tauri_build::try_build(attributes).expect("build Tauri application metadata");
    prune_retired_command_permissions();
}

/// Deletes the generated permission files of commands that no longer exist.
///
/// `tauri_build::try_build` writes one `permissions/autogenerated/<command>.toml` per entry
/// of `APP_COMMANDS`, but it only ever *adds*: retiring a command leaves its file behind
/// forever. The directory is gitignored build output, so the residue is invisible to review
/// and survives every rebuild — the ACL then advertises `allow-<retired-command>` identifiers
/// that no command and no capability back.
///
/// Only files this build script's own generator could have written are considered: a
/// `<stem>.toml` directly in the directory, carrying tauri-build's header, whose stem is not
/// a live command. Anything else is left alone.
fn prune_retired_command_permissions() {
    let directory = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"))
        .join("permissions")
        .join("autogenerated");
    let Ok(entries) = fs::read_dir(&directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("toml") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        if APP_COMMANDS.contains(&stem) {
            continue;
        }
        // A hand-written permission file that happens to sit here is not this script's to
        // delete; the header is what marks the file as generated.
        if !matches!(fs::read_to_string(&path), Ok(text) if text.starts_with("# Automatically generated")) {
            continue;
        }
        if fs::remove_file(&path).is_ok() {
            println!("cargo:warning=删除已退役命令的权限文件 {stem}.toml");
        }
    }
}

/// Stages the AI SDK sidecar where `externalBin` expects it.
///
/// `tauri.conf.json` declares `binaries/mework-aisdk`, and Tauri resolves that to
/// `binaries/mework-aisdk-<target-triple><exe>`. If the file is absent, *every* build fails —
/// `cargo check` and `cargo test` included — with a message that says nothing about how to fix
/// it. That is a bad first five minutes for a fresh clone, so this stages the artifact itself.
///
/// The triple comes from `TARGET`, which Cargo sets for the build script. That is the
/// authoritative value; deriving it a second time by parsing `rustc -vV` elsewhere would only
/// create a second thing that can drift. `scripts/build-aisdk-sidecar.mjs` therefore only
/// *builds* `aisdk-service/dist/`; naming and placement live here alone.
///
/// The copy is skipped when the staged file already matches the built one by size and mtime:
/// the sidecar is ~90 MiB and this runs on every build script invocation.
fn stage_aisdk_sidecar() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let repo = manifest.parent().expect("repository root").to_path_buf();
    let exe_suffix = if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        ".exe"
    } else {
        ""
    };
    let built = repo
        .join("aisdk-service")
        .join("dist")
        .join(format!("mework-aisdk{exe_suffix}"));
    println!("cargo:rerun-if-changed={}", built.display());

    let target = env::var("TARGET").expect("TARGET is set by Cargo for build scripts");
    // The crate needs the same triple at runtime to find the staged copy (the aisdk tests look
    // for exactly the file this function guarantees). Exporting it here keeps one owner for the
    // value instead of parsing `rustc -vV` a second time somewhere else.
    println!("cargo:rustc-env=MEWORK_TARGET_TRIPLE={target}");
    let staged = manifest
        .join("binaries")
        .join(format!("mework-aisdk-{target}{exe_suffix}"));
    println!("cargo:rerun-if-changed={}", staged.display());

    let built_meta = fs::metadata(&built).ok();
    let Some(built_meta) = built_meta else {
        // Nothing to stage from. An already-staged copy is fine — that is the packaging box,
        // where `beforeBuildCommand` produced it and `aisdk-service/` may not even be present.
        assert!(
            staged.is_file(),
            "AI SDK 侧车缺席，Tauri 的 externalBin 找不到 {}。\n\
             先跑 `npm run build:sidecar`（会在 aisdk-service/ 里打出单文件可执行），\n\
             或者在 aisdk-service/ 里跑 `npm run build:sea`。",
            staged.display(),
        );
        return;
    };

    if let Ok(staged_meta) = fs::metadata(&staged) {
        let same_size = staged_meta.len() == built_meta.len();
        let fresh = match (staged_meta.modified(), built_meta.modified()) {
            (Ok(staged_at), Ok(built_at)) => staged_at >= built_at,
            _ => false,
        };
        if same_size && fresh {
            return;
        }
    }

    fs::create_dir_all(staged.parent().expect("binaries directory"))
        .expect("create the sidecar staging directory");
    fs::copy(&built, &staged).expect("stage the AI SDK sidecar for externalBin");
}


///
/// tauri-build (via tauri-winres/embed-resource) attaches the manifest with
/// `cargo:rustc-link-arg-bins`, which cargo test harnesses never receive. Without a manifest
/// declaring the Common-Controls v6 dependency, the loader resolves comctl32.dll to the legacy
/// v5 copy in System32, which lacks `TaskDialogIndirect` (imported through muda/rfd), and MSVC
/// test executables die at load with STATUS_ENTRYPOINT_NOT_FOUND. Linking the explicit manifest
/// everywhere also makes GNU ld drop MinGW's default manifest object, leaving each executable
/// with exactly one RT_MANIFEST.
fn embed_windows_manifest_for_all_link_targets(output_dir: &Path) -> bool {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return false;
    }
    let manifest_path = output_dir.join("mework-app.manifest");
    fs::write(&manifest_path, include_str!("windows-app-manifest.xml"))
        .expect("write Windows application manifest");
    let resource_path = output_dir.join("mework-manifest.rc");
    let resource_manifest_path = manifest_path.to_string_lossy().replace('\\', "/");
    fs::write(
        &resource_path,
        format!("1 24 \"{resource_manifest_path}\"\n"),
    )
    .expect("write Windows manifest resource script");

    match env::var("CARGO_CFG_TARGET_ENV").as_deref() {
        Ok("gnu") => {
            let object_name = "mework-manifest.o";
            let windres = ["windres", "x86_64-w64-mingw32-windres"]
                .into_iter()
                .find(|name| {
                    Command::new(name)
                        .arg("--version")
                        .output()
                        .is_ok_and(|output| output.status.success())
                })
                .expect("windres is required to embed the Windows manifest on windows-gnu");
            let status = Command::new(windres)
                .current_dir(output_dir)
                .args(["-O", "coff", "-i", "mework-manifest.rc", "-o", object_name])
                .status()
                .expect("run windres");
            assert!(status.success(), "windres failed with {status}");
            println!(
                "cargo:rustc-link-arg={}",
                output_dir.join(object_name).display()
            );
            true
        }
        Ok("msvc") => {
            embed_resource::compile_for_everything(&resource_path, embed_resource::NONE)
                .manifest_required()
                .expect("compile Windows application manifest for all MSVC targets");
            true
        }
        _ => false,
    }
}

fn prefer_mingw_toolchain() {
    #[cfg(all(windows, target_env = "gnu"))]
    {
        let Some(path) = env::var_os("PATH") else {
            return;
        };
        let entries = env::split_paths(&path).collect::<Vec<_>>();
        let Some(mingw_bin) = entries
            .iter()
            .find(|entry| {
                entry
                    .components()
                    .rev()
                    .take(2)
                    .map(|part| part.as_os_str().to_string_lossy().to_lowercase())
                    .collect::<Vec<_>>()
                    == ["bin", "mingw64"]
            })
            .cloned()
        else {
            return;
        };
        let reordered = std::iter::once(mingw_bin.clone())
            .chain(entries.into_iter().filter(|entry| entry != &mingw_bin))
            .collect::<Vec<_>>();
        if let Ok(path) = env::join_paths(reordered) {
            env::set_var("PATH", path);
        }
    }
}

fn generated_icon() -> Vec<u8> {
    let options = resvg::usvg::Options::default();
    let tree = resvg::usvg::Tree::from_data(APP_ICON_SVG, &options)
        .expect("parse the canonical Mework SVG icon");
    let png_images = APP_ICON_SIZES
        .into_iter()
        .map(|size| {
            let mut pixmap =
                resvg::tiny_skia::Pixmap::new(size, size).expect("allocate Mework icon pixmap");
            let transform = resvg::tiny_skia::Transform::from_scale(
                size as f32 / tree.size().width(),
                size as f32 / tree.size().height(),
            );
            resvg::render(&tree, transform, &mut pixmap.as_mut());
            pixmap.encode_png().expect("encode Mework icon PNG")
        })
        .collect::<Vec<_>>();

    let directory_bytes = 6 + png_images.len() * 16;
    let image_bytes = png_images.iter().map(Vec::len).sum::<usize>();
    let mut icon = Vec::with_capacity(directory_bytes + image_bytes);
    icon.extend_from_slice(&0_u16.to_le_bytes());
    icon.extend_from_slice(&1_u16.to_le_bytes());
    icon.extend_from_slice(&(png_images.len() as u16).to_le_bytes());

    let mut image_offset = directory_bytes as u32;
    for (size, png) in APP_ICON_SIZES.into_iter().zip(&png_images) {
        let directory_size = if size == 256 { 0 } else { size as u8 };
        icon.extend_from_slice(&[directory_size, directory_size, 0, 0]);
        icon.extend_from_slice(&1_u16.to_le_bytes());
        icon.extend_from_slice(&32_u16.to_le_bytes());
        icon.extend_from_slice(&(png.len() as u32).to_le_bytes());
        icon.extend_from_slice(&image_offset.to_le_bytes());
        image_offset += png.len() as u32;
    }
    for png in png_images {
        icon.extend_from_slice(&png);
    }
    icon
}
