//! The Claude Code plugin that keeps the CLI's own context out of the prompt.
//!
//! Left to itself the CLI attaches context it authors — an `# Environment` block
//! (the directory it runs in, which is Mework's private session folder, its
//! platform, shell and OS version), a model-identity line and today's date — to
//! the first user message, whatever the system prompt is. None of it is Mework's
//! to leave there: one Mework conversation can run on several machines, and only
//! the host knows which facts hold for which of them, so the host's own
//! environment prompt is the only one the model may see. Since Claude Code 2.1.278
//! no switch turns this off short of `--bare`, and bare mode never reads the OAuth
//! login this family runs on.
//!
//! What remains is the CLI's own hooks-module ("function hooks") surface: a
//! plugin's module may answer the `prompt.attachment` event, which every rendered
//! attachment passes through before a model call, with `{ text: null }` — "leave
//! it out". The CLI loads such modules only under `CLAUDE_CODE_ENABLE_FUNCTION_HOOKS`
//! (still early access), so this depends on the CLI version exactly as the old
//! switch did; `selfcheck-claude-agent.mjs` asserts the first upstream request
//! carries nothing the CLI authored.
//!
//! The plugin is a handful of text files, generated here rather than shipped as a
//! resource, and written content-addressed under the private session directory the
//! host hands over (`agent.cwd`): a directory whose name is the digest of its
//! contents is complete or absent, and an edit here lands in a new one.

import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

/** Plugin name; the CLI reports it as `mework-context@inline`. */
export const CONTEXT_PLUGIN_NAME = "mework-context";

/**
 * CLI attachment types the plugin leaves out: the environment block and its
 * `# Environment update` diffs, the model-identity line, and the date (with its
 * midnight-rollover notice). The host's environment prompt states all of these
 * itself, per machine.
 */
export const CLI_CONTEXT_ATTACHMENTS = ["environment", "model", "date", "date_change"] as const;

/**
 * The hooks module. The CLI refuses a module that touches `$` other than as
 * `$.noun.event(...)`, and this one never touches it: every other attachment
 * passes on unchanged through `next`.
 */
const HOOKS_MODULE = `// Generated by Mework (aisdk-service/src/claude-context-plugin.ts).
const LEFT_OUT = ${JSON.stringify(CLI_CONTEXT_ATTACHMENTS)};
export const register = (on) => {
  on("prompt.attachment", ($, e, next) => (LEFT_OUT.includes(e.type) ? { text: null } : next(e)));
};
`;

/** Plugin files by path relative to the plugin root. */
const PLUGIN_FILES: ReadonlyArray<readonly [string, string]> = [
  [
    path.join(".claude-plugin", "plugin.json"),
    `${JSON.stringify(
      {
        name: CONTEXT_PLUGIN_NAME,
        version: "1.0.0",
        description: "Leaves Claude Code's own environment, model and date context out of the prompt; Mework supplies its own.",
      },
      null,
      2,
    )}\n`,
  ],
  [path.join("hooks", "hooks.json"), `${JSON.stringify({ modules: ["./context.ts"] }, null, 2)}\n`],
  [path.join("hooks", "context.ts"), HOOKS_MODULE],
];

const DIGEST = (() => {
  const hash = createHash("sha256");
  for (const [relative, text] of PLUGIN_FILES) hash.update(relative).update("\0").update(text).update("\0");
  return hash.digest("hex").slice(0, 16);
})();

/** Parent directory of the plugin, under the session directory. */
const PLUGINS_DIR = "plugins";

function isComplete(dir: string): boolean {
  return PLUGIN_FILES.every(([relative, text]) => {
    try {
      return readFileSync(path.join(dir, relative), "utf8") === text;
    } catch {
      return false;
    }
  });
}

/** Earlier builds' copies and staging left by a crash; nothing else lives under `plugins/`. */
function removeStale(parent: string, current: string): void {
  let entries: string[];
  try {
    entries = readdirSync(parent);
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry === current || !entry.replace(/^\./, "").startsWith(`${CONTEXT_PLUGIN_NAME}-`)) continue;
    rmSync(path.join(parent, entry), { recursive: true, force: true });
  }
}

const materialized = new Map<string, string>();

/**
 * The plugin directory under `root`, written on first use. Staged beside its final
 * name and renamed into place, so the CLI never loads a half-written copy.
 * Throws when it cannot be written: a session without the plugin would show the
 * model the CLI's context, so it must not start.
 */
export function contextPluginDir(root: string): string {
  const known = materialized.get(root);
  if (known !== undefined && isComplete(known)) return known;
  const parent = path.join(root, PLUGINS_DIR);
  const name = `${CONTEXT_PLUGIN_NAME}-${DIGEST}`;
  const dir = path.join(parent, name);
  if (!isComplete(dir)) {
    rmSync(dir, { recursive: true, force: true });
    const staging = path.join(parent, `.${name}.${randomUUID()}`);
    try {
      for (const [relative, text] of PLUGIN_FILES) {
        const file = path.join(staging, relative);
        mkdirSync(path.dirname(file), { recursive: true });
        writeFileSync(file, text);
      }
      renameSync(staging, dir);
    } finally {
      rmSync(staging, { recursive: true, force: true });
    }
  }
  removeStale(parent, name);
  materialized.set(root, dir);
  return dir;
}
