// Builds the static documentation site under website/dist from the Markdown
// sources in website/content/<lang>/*.md and the per-tool notes in
// website/content/<lang>/tools/<name>.md.
//
// Usage: node scripts/build-site.mjs [--out <dir>]
//
// The build is deliberately dependency-light: `marked` for Markdown, no
// framework. Each page is one Markdown file; the first `# ` heading is its
// title. Generated content comes from the design baselines in
// docs/context-injections/ (regenerated by the Rust golden tests, so the site
// cannot drift from the code):
//
// - `{{TOOL_TABLE:<name>,<name>,…}}` on the tools page — an index table of the
//   named tools, each linking to its own page under tools/. The page's headings
//   are the groups: every catalog tool must sit in exactly one table. Each tool
//   page's breadcrumb is the heading path it sits under.
// - tools/<name>.html — one page per catalog tool: the hand-written notes, the
//   parameter table from the schema baseline, and the description the built-in
//   profile gives the model.
// - `{{PROMPT_KEYS_LIST}}` on the prompt-profiles page — the injection-point
//   reference (key, placeholders, where it is injected), grouped by prefix. The
//   built-in texts themselves are in the downloadable profile file.
// - `{{PROFILE_FILE_LINKS}}` — download links for that file and the key manifest.
// - `{{TOOL_COUNT}}` / `{{SWITCHABLE_TOOL_COUNT}}` / `{{DERIVED_TOOL_COUNT}}` —
//   the catalog sizes, so prose never carries a stale number.

import { marked } from "marked";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..");
const contentRoot = path.join(repo, "website", "content");
const assetsRoot = path.join(repo, "website", "assets");
const baselineRoot = path.join(repo, "docs", "context-injections");

const args = process.argv.slice(2);
function option(name, fallback) {
  const index = args.indexOf(name);
  return index >= 0 && args[index + 1] ? args[index + 1] : fallback;
}
const outRoot = path.resolve(repo, option("--out", "website/dist"));

const LANGUAGES = [
  { code: "en", label: "English", htmlLang: "en", dir: "en", catalog: "en-US" },
  { code: "zh-CN", label: "简体中文", htmlLang: "zh-CN", dir: "zh-CN", catalog: "zh-CN" },
];
const PAGES = ["index", "working", "tools", "prompt-profiles", "skills", "mcp", "lsp", "hooks"];
// Short navigation labels; page titles (first heading) stay descriptive.
const NAV_LABELS = {
  en: { index: "Overview", working: "Working with Mework", tools: "Tools", "prompt-profiles": "Prompt profiles", skills: "Skills", mcp: "MCP", lsp: "Code navigation", hooks: "Hooks" },
  "zh-CN": { index: "概览", working: "使用方法", tools: "工具", "prompt-profiles": "提示词档案", skills: "技能", mcp: "MCP", lsp: "代码语义导航", hooks: "钩子" },
};
const UI = {
  en: {
    siteName: "Mework docs",
    github: "GitHub",
    onThisPage: "On this page",
    languages: "Language",
    footer: "Mework is released under GPL-3.0-or-later. This site is built from website/content in the repository.",
    keyTable: { id: "Key", placeholders: "Placeholders", where: "Where it is injected" },
    downloads: { builtin: "Download the built-in profile (prompt-profile.en-US.json)", manifest: "Download the key manifest (prompt-profile-keys.json)" },
    tools: {
      tool: "Tool",
      name: "Name",
      summary: "What it does",
      availability: "Availability",
      switchable: "Tool picker",
      parameters: "Parameters",
      parameter: "Parameter",
      type: "Type",
      required: "Required",
      def: "Default",
      description: "Description",
      yes: "yes",
      no: "no",
      noParameters: "This tool takes no parameters.",
      variants: "The call takes one of these shapes, selected by",
      modelText: "What the model is told",
      modelTextNote: "This is the tool's root schema description from the built-in profile. A tool-description file can replace it with `schemaNotes`.",
      profileKey: "Profile key",
      backToIndex: "All tools",
      reviewed: "Reviewed",
      reviewedNote: "Marked “Reviewed” in the tool picker: calls are classified as writes or as unbounded actions and ask for approval unless the security level or a standing allowance covers them.",
    },
    derived: {
      memory: "Derived from the global / project memory switch",
      task: "Derived: present whenever a task-producing tool is enabled",
      plan: "Derived from the security level: Plan mode only",
      web: "Derived from the conversation's web-access switch",
      skill: "Derived from the on-demand skill switch",
      tool_search: "Derived from the MCP tool-discovery switch",
      preview: "Follows the other preview tools: on whenever any of them is enabled",
    },
  },
  "zh-CN": {
    siteName: "Mework 文档",
    github: "GitHub",
    onThisPage: "本页目录",
    languages: "语言",
    footer: "Mework 以 GPL-3.0-or-later 许可发布。本站由仓库中的 website/content 构建。",
    keyTable: { id: "键", placeholders: "占位符", where: "注入位置" },
    downloads: { builtin: "下载内置档案（prompt-profile.en-US.json）", manifest: "下载键清单（prompt-profile-keys.json）" },
    tools: {
      tool: "工具",
      name: "名称",
      summary: "作用",
      availability: "可用性",
      switchable: "工具选择器",
      parameters: "参数",
      parameter: "参数",
      type: "类型",
      required: "必填",
      def: "默认值",
      description: "说明",
      yes: "是",
      no: "否",
      noParameters: "这个工具没有参数。",
      variants: "调用取以下形态之一，由此字段选择：",
      modelText: "模型读到的描述",
      modelTextNote: "这是内置档案里该工具的 schema 根描述，模型读到的就是这段英文。工具描述文件可以用 `schemaNotes` 替换它。",
      profileKey: "档案键",
      backToIndex: "全部工具",
      reviewed: "需审查",
      reviewedNote: "在工具选择器里标为「需审查」：调用被归类为写入或无界操作，除非安全级别或已有的常设允许覆盖，否则需要审批。",
    },
    derived: {
      memory: "派生自全局 / 项目记忆开关",
      task: "派生：只要启用了任何会产生任务的工具就存在",
      plan: "派生自安全级别：仅计划模式",
      web: "派生自对话的联网开关",
      skill: "派生自技能按需加载开关",
      tool_search: "派生自 MCP 工具发现开关",
      preview: "跟随其余预览工具：只要启用了其中任何一个就启用",
    },
  },
};

// Tools the tool picker does not list: the host derives them from a switch, or,
// for the preview lifecycle tools, the picker keeps them in step with the other
// preview tools. Mirrors src/lib/taskTools.ts (isHostDerivedToolName,
// isPreviewLifecycleToolName) and src/lib/memoryTools.ts.
const DERIVED = {
  read_global_memory: "memory", read_project_memory: "memory", create_global_memory: "memory",
  create_project_memory: "memory", edit_global_memory: "memory", edit_project_memory: "memory",
  task_wait: "task", task_list: "task", box: "task",
  plan: "plan", exit_plan_mode: "plan",
  web_search: "web", web_fetch: "web",
  skill: "skill",
  tool_search: "tool_search",
  preview_start: "preview", preview_stop: "preview", preview_list: "preview",
};
function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/<[^>]+>/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "") || "section";
}

/** The catalog, the schema baseline, the built-in profile's texts and the key
 * manifest, read once. The profile is English on every page: it is what the
 * model reads, whatever language the site is in. */
const baseline = {
  catalog: Object.fromEntries(LANGUAGES.map((language) => [
    language.code,
    readJson(path.join(baselineRoot, `builtin-tool-catalog.${language.catalog}.json`)).tools,
  ])),
  schemas: Object.fromEntries(readJson(path.join(baselineRoot, "builtin-tool-schemas.json")).tools.map((tool) => [tool.name, tool.schema])),
  prompts: readJson(path.join(baselineRoot, "prompt-profile.en-US.json")).prompts,
  keys: readJson(path.join(baselineRoot, "prompt-profile-keys.json")).keys,
};

/** The profile key that carries a tool's root schema description. */
function toolDescriptionKey(name) {
  if (name === "skill") return "skill.tool_description";
  if (name === "tool_search") return "tool_search.tool_description";
  return `tool.${name}.description`;
}

function toolDescription(name) {
  return baseline.prompts[toolDescriptionKey(name)] ?? baseline.schemas[name]?.description ?? "";
}

function firstSentence(text) {
  const flat = text.replace(/\s+/g, " ").trim();
  const match = /^(.+?)(?:\.\s|。|$)/u.exec(flat);
  let sentence = match ? match[1] : flat;
  if (/[。]$/u.test(flat.slice(sentence.length, sentence.length + 1))) sentence += "。";
  else if (sentence !== flat) sentence += ".";
  return sentence.length > 200 ? `${sentence.slice(0, 197)}…` : sentence;
}

function inlineCode(text) {
  return escapeHtml(text).replace(/`([^`]+)`/g, "<code>$1</code>");
}

function availabilityLabel(lang, name) {
  const ui = UI[lang];
  if (DERIVED[name]) return ui.derived[DERIVED[name]];
  return ui.tools.switchable;
}

function toolCounts() {
  const all = baseline.catalog.en.length;
  const derived = baseline.catalog.en.filter((tool) => DERIVED[tool.name]).length;
  return { all, derived, switchable: all - derived };
}

/** An index table of the named tools, for a `{{TOOL_TABLE:…}}` on the tools page. */
function toolTable(lang, names) {
  const ui = UI[lang];
  const rows = names.map((name) => {
    const tool = baseline.catalog[lang].find((candidate) => candidate.name === name);
    return `<tr>
  <td><a href="tools/${escapeHtml(tool.name)}.html"><code>${escapeHtml(tool.name)}</code></a></td>
  <td>${escapeHtml(tool.label)}</td>
  <td>${inlineCode(firstSentence(toolDescription(tool.name)))}</td>
  <td class="availability">${inlineCode(availabilityLabel(lang, tool.name))}</td>
</tr>`;
  });
  return `<div class="table-scroll"><table class="tool-index">
<thead><tr><th>${ui.tools.tool}</th><th>${ui.tools.name}</th><th>${ui.tools.summary}</th><th>${ui.tools.availability}</th></tr></thead>
<tbody>
${rows.join("\n")}
</tbody></table></div>`;
}

/** A heading's anchor id and inline HTML, the way `renderMarkdown` renders it. */
function headingAnchor(source) {
  let text = marked.parseInline(source);
  let id = slugify(text);
  const explicit = /\s*\{#([A-Za-z0-9_-]+)\}\s*$/.exec(text);
  if (explicit) {
    id = explicit[1];
    text = text.slice(0, explicit.index);
  }
  return { id, text };
}

/**
 * Expands the tools page's `{{TOOL_TABLE:…}}` placeholders and works out where
 * each tool sits: the path of headings (h2 down to h4) above its table, which
 * its own page shows as a breadcrumb. Refuses a page that leaves a catalog tool
 * out, lists one twice, or names one the catalog does not have.
 */
function placeTools(markdown, lang) {
  const catalog = new Set(baseline.catalog[lang].map((tool) => tool.name));
  const placements = new Map();
  const path = [];
  const lines = markdown.split("\n").map((line) => {
    const heading = /^(#{2,4})\s+(.+)$/.exec(line);
    if (heading) {
      const depth = heading[1].length;
      path.length = depth - 2;
      path.push(headingAnchor(heading[2]));
      return line;
    }
    return line.replace(/\{\{TOOL_TABLE:([^}]+)\}\}/g, (_, list) => {
      const names = list.split(",").map((name) => name.trim()).filter(Boolean);
      for (const name of names) {
        if (!catalog.has(name)) throw new Error(`${lang}/tools.md lists a tool the catalog does not have: ${name}`);
        if (placements.has(name)) throw new Error(`${lang}/tools.md lists ${name} twice`);
        placements.set(name, path.filter(Boolean).map((entry) => ({ ...entry })));
      }
      return toolTable(lang, names);
    });
  });
  const missing = [...catalog].filter((name) => !placements.has(name));
  if (missing.length) throw new Error(`${lang}/tools.md leaves out: ${missing.join(", ")}`);
  return { markdown: lines.join("\n"), placements };
}

/** One row of a parameter table from a JSON Schema property. */
function schemaConstraints(schema) {
  const parts = [];
  if (schema.enum) parts.push(`one of ${schema.enum.map((value) => `<code>${escapeHtml(JSON.stringify(value))}</code>`).join(", ")}`);
  if (schema.const !== undefined) parts.push(`<code>${escapeHtml(JSON.stringify(schema.const))}</code>`);
  if (schema.minimum !== undefined || schema.maximum !== undefined) {
    parts.push(`${schema.minimum !== undefined ? `≥ ${schema.minimum}` : ""}${schema.minimum !== undefined && schema.maximum !== undefined ? ", " : ""}${schema.maximum !== undefined ? `≤ ${schema.maximum}` : ""}`);
  }
  if (schema.minLength !== undefined && schema.minLength > 1) parts.push(`min length ${schema.minLength}`);
  if (schema.maxLength !== undefined) parts.push(`max length ${schema.maxLength.toLocaleString("en-US")}`);
  if (schema.minItems !== undefined) parts.push(`min items ${schema.minItems}`);
  if (schema.maxItems !== undefined) parts.push(`max items ${schema.maxItems}`);
  if (schema.pattern) parts.push(`pattern <code>${escapeHtml(schema.pattern)}</code>`);
  if (schema.items?.type) parts.push(`items: ${schema.items.type}`);
  return parts;
}

function schemaType(schema) {
  if (schema.const !== undefined) return "const";
  if (Array.isArray(schema.type)) return schema.type.join(" | ");
  if (schema.type) return schema.type;
  if (schema.enum) return "enum";
  if (schema.oneOf || schema.anyOf) return "object";
  return "any";
}

function parameterTable(lang, schema, catalogTool) {
  const ui = UI[lang].tools;
  const properties = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const names = Object.keys(properties);
  if (!names.length) return `<p>${ui.noParameters}</p>`;
  const labels = Object.fromEntries((catalogTool?.parameters ?? []).map((parameter) => [parameter.name, parameter]));
  const rows = names.map((name) => {
    const property = properties[name];
    const label = labels[name]?.label && labels[name].label !== name ? `<br><span class="param-label">${escapeHtml(labels[name].label)}</span>` : "";
    const description = [property.description ? inlineCode(property.description) : "", ...schemaConstraints(property).map((part) => `<span class="constraint">${part}</span>`)]
      .filter(Boolean)
      .join("<br>");
    const fallback = !property.description && labels[name]?.help ? inlineCode(labels[name].help) : "";
    return `<tr>
  <td><code>${escapeHtml(name)}</code>${label}</td>
  <td>${escapeHtml(schemaType(property))}</td>
  <td>${required.has(name) ? ui.yes : ui.no}</td>
  <td>${property.default !== undefined ? `<code>${escapeHtml(JSON.stringify(property.default))}</code>` : "—"}</td>
  <td>${description || fallback || "—"}</td>
</tr>`;
  });
  return `<div class="table-scroll"><table class="param-table">
<thead><tr><th>${ui.parameter}</th><th>${ui.type}</th><th>${ui.required}</th><th>${ui.def}</th><th>${ui.description}</th></tr></thead>
<tbody>
${rows.join("\n")}
</tbody></table></div>`;
}

/** Parameter documentation for one tool; multi-shape schemas get one table per shape. */
function parameterSection(lang, name) {
  const ui = UI[lang].tools;
  const schema = baseline.schemas[name];
  const catalogTool = baseline.catalog[lang].find((tool) => tool.name === name);
  if (!schema) return "";
  const variants = schema.oneOf ?? schema.anyOf;
  if (Array.isArray(variants) && variants.length && variants.every((variant) => variant.properties)) {
    const discriminator = Object.keys(variants[0].properties).find((key) => variants.every((variant) => variant.properties?.[key]?.const !== undefined));
    const blocks = variants.map((variant) => {
      const value = discriminator ? variant.properties[discriminator].const : undefined;
      const heading = value !== undefined ? `<h4 id="${escapeHtml(name)}-${escapeHtml(String(value))}"><code>${escapeHtml(discriminator)}: ${escapeHtml(JSON.stringify(value))}</code></h4>` : "";
      const intro = variant.description ? `<p>${inlineCode(variant.description)}</p>` : "";
      return `${heading}\n${intro}\n${parameterTable(lang, variant, catalogTool)}`;
    });
    const lead = discriminator ? `<p>${ui.variants} <code>${escapeHtml(discriminator)}</code>.</p>` : "";
    return `${lead}\n${blocks.join("\n")}`;
  }
  return parameterTable(lang, schema, catalogTool);
}

function renderToolPage(lang, tool, notesMarkdown, trail) {
  const ui = UI[lang];
  const description = toolDescription(tool.name);
  const key = toolDescriptionKey(tool.name);
  const { html: notesHtml, outline } = renderMarkdown(notesMarkdown, lang);
  const breadcrumb = [
    `<a href="../tools.html">${ui.tools.backToIndex}</a>`,
    ...trail.map((heading) => `<a href="../tools.html#${heading.id}">${heading.text}</a>`),
  ];
  const meta = [
    `<span><strong>${ui.tools.availability}</strong> ${inlineCode(availabilityLabel(lang, tool.name))}</span>`,
    `<span><strong>${ui.tools.profileKey}</strong> <a href="../prompt-profiles.html#key-${escapeHtml(key).replace(/\./g, "-")}"><code>${escapeHtml(key)}</code></a></span>`,
  ];
  if (tool.dangerous) meta.push(`<span class="reviewed" title="${escapeHtml(ui.tools.reviewedNote)}"><strong>${ui.tools.reviewed}</strong></span>`);
  const parametersId = "parameters";
  const modelTextId = "model-description";
  outline.push({ id: parametersId, text: ui.tools.parameters }, { id: modelTextId, text: ui.tools.modelText });
  const html = `<p class="breadcrumb">${breadcrumb.join(" › ")}</p>
<h1 id="${escapeHtml(tool.name)}"><code>${escapeHtml(tool.name)}</code> <span class="tool-label">${escapeHtml(tool.label)}</span></h1>
<p class="tool-meta">${meta.join("")}</p>
${notesHtml}
<h2 id="${parametersId}"><a class="anchor" href="#${parametersId}">${ui.tools.parameters}</a></h2>
${parameterSection(lang, tool.name)}
<h2 id="${modelTextId}"><a class="anchor" href="#${modelTextId}">${ui.tools.modelText}</a></h2>
<p class="muted">${inlineCode(ui.tools.modelTextNote)}</p>
<pre class="model-text">${escapeHtml(description)}</pre>`;
  return { html, outline, title: `${tool.name} — ${tool.label}` };
}

/** Renders the compact injection-point reference (key, placeholders, where). */
function promptKeysList(lang) {
  const labels = UI[lang].keyTable;
  const groups = new Map();
  for (const key of baseline.keys) {
    const prefix = key.id.split(".")[0];
    if (!groups.has(prefix)) groups.set(prefix, []);
    groups.get(prefix).push(key);
  }
  const toolNames = new Set(baseline.catalog.en.map((tool) => tool.name));
  const sections = [];
  for (const [prefix, keys] of groups) {
    const id = `keys-${prefix.replace(/[^a-z0-9_-]/gi, "-")}`;
    const rows = keys.map((key) => {
      const placeholders = key.placeholders.length
        ? key.placeholders.map((name) => `<code>{${escapeHtml(name)}}</code>`).join(" ")
        : "—";
      const toolMatch = /^tool\.([a-z_]+)\.description$/.exec(key.id);
      const toolLink = toolMatch && toolNames.has(toolMatch[1])
        ? ` <a class="tool-link" href="tools/${toolMatch[1]}.html">↗</a>`
        : "";
      return `<tr id="key-${escapeHtml(key.id).replace(/\./g, "-")}">
  <td><code>${escapeHtml(key.id)}</code>${toolLink}</td>
  <td>${placeholders}</td>
  <td>${inlineCode(key.description)}</td>
</tr>`;
    });
    sections.push(`<h3 id="${id}"><a class="anchor" href="#${id}"><code>${escapeHtml(prefix)}.*</code></a></h3>
<div class="table-scroll"><table class="key-table">
<thead><tr><th>${labels.id}</th><th>${labels.placeholders}</th><th>${labels.where}</th></tr></thead>
<tbody>
${rows.join("\n")}
</tbody></table></div>`);
  }
  return sections.join("\n");
}

function profileFileLinks(lang) {
  const labels = UI[lang].downloads;
  return `<ul class="downloads">
<li><a href="../files/prompt-profile.en-US.json" download>${labels.builtin}</a></li>
<li><a href="../files/prompt-profile-keys.json" download>${labels.manifest}</a></li>
</ul>`;
}

/** Markdown → HTML with heading ids and a collected outline. */
function renderMarkdown(markdown, lang) {
  const outline = [];
  const renderer = new marked.Renderer();
  // A heading may end in `{#custom-id}` so that anchors survive translation:
  // the id is shared across languages while the visible text is not.
  renderer.heading = ({ tokens, depth }) => {
    let text = renderer.parser.parseInline(tokens);
    let id = slugify(text);
    const explicit = /\s*\{#([A-Za-z0-9_-]+)\}\s*$/.exec(text);
    if (explicit) {
      id = explicit[1];
      text = text.slice(0, explicit.index);
    }
    if (depth === 2) outline.push({ id, text });
    return `<h${depth} id="${id}"><a class="anchor" href="#${id}">${text}</a></h${depth}>\n`;
  };
  const counts = toolCounts();
  const expanded = markdown
    .replace(/\{\{PROMPT_KEYS_LIST\}\}/g, () => promptKeysList(lang))
    .replace(/\{\{PROFILE_FILE_LINKS\}\}/g, () => profileFileLinks(lang))
    .replace(/\{\{TOOL_COUNT\}\}/g, String(counts.all))
    .replace(/\{\{SWITCHABLE_TOOL_COUNT\}\}/g, String(counts.switchable))
    .replace(/\{\{DERIVED_TOOL_COUNT\}\}/g, String(counts.derived));
  const html = marked.parse(expanded, { renderer, gfm: true });
  return { html, outline };
}

function pageTitle(markdown, fallback) {
  const match = /^#\s+(.+)$/m.exec(markdown);
  return match ? match[1].replace(/\s*\{#[A-Za-z0-9_-]+\}\s*$/, "").trim() : fallback;
}

/**
 * The shared chrome. `page` picks the highlighted navigation entry, `slug` is
 * the page's path below <lang>/ without the extension (the same in every
 * language, which is what the language switch links to), and `depth` is how
 * many directories below <lang>/ the page sits. Every link is relative so the
 * site works from any base path.
 */
function layout({ lang, page, slug = page, title, html, outline, titles, depth = 0 }) {
  const ui = UI[lang];
  const up = "../".repeat(depth);
  const root = "../".repeat(depth + 1);
  const nav = PAGES.map((candidate) =>
    `<a href="${up}${candidate}.html"${candidate === page ? ' class="active"' : ""}>${escapeHtml(NAV_LABELS[lang][candidate] ?? titles[candidate])}</a>`
  ).join("\n        ");
  const languageLinks = LANGUAGES.map((candidate) =>
    candidate.code === lang
      ? `<span class="active">${candidate.label}</span>`
      : `<a href="${root}${candidate.dir}/${slug}.html" hreflang="${candidate.htmlLang}">${candidate.label}</a>`
  ).join(" · ");
  const toc = outline.length
    ? `<aside class="toc"><h3>${ui.onThisPage}</h3><ul>${outline.map((item) => `<li><a href="#${item.id}">${item.text}</a></li>`).join("")}</ul></aside>`
    : "";
  return `<!DOCTYPE html>
<html lang="${LANGUAGES.find((candidate) => candidate.code === lang).htmlLang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)} · ${ui.siteName}</title>
<link rel="stylesheet" href="${root}assets/style.css">
<link rel="icon" href="${root}assets/mework-icon-small.svg" type="image/svg+xml">
</head>
<body>
<header class="site-header">
  <div class="site-header__inner">
    <a class="brand" href="${up}index.html"><img src="${root}assets/mework-icon-small.svg" alt="" width="28" height="28"> <span>${ui.siteName}</span></a>
    <nav class="site-nav">
        ${nav}
    </nav>
    <div class="site-header__right">
      <span class="languages" aria-label="${ui.languages}">${languageLinks}</span>
      <a class="github" href="https://github.com/catblob-hash/Mework">${ui.github}</a>
    </div>
  </div>
</header>
<div class="page">
  <main class="content">
${html}
  </main>
  ${toc}
</div>
<footer class="site-footer">${ui.footer}</footer>
</body>
</html>
`;
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const source = path.join(from, entry.name);
    const target = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(source, target);
    else fs.copyFileSync(source, target);
  }
}

function build() {
  fs.rmSync(outRoot, { recursive: true, force: true });
  fs.mkdirSync(outRoot, { recursive: true });
  copyDir(assetsRoot, path.join(outRoot, "assets"));
  fs.copyFileSync(path.join(repo, "src", "mework-icon.svg"), path.join(outRoot, "assets", "mework-icon.svg"));
  fs.copyFileSync(path.join(repo, "src", "mework-icon-small.svg"), path.join(outRoot, "assets", "mework-icon-small.svg"));
  const filesDir = path.join(outRoot, "files");
  fs.mkdirSync(filesDir, { recursive: true });
  for (const name of ["prompt-profile.en-US.json", "prompt-profile-keys.json"]) {
    fs.copyFileSync(path.join(baselineRoot, name), path.join(filesDir, name));
  }
  fs.writeFileSync(path.join(outRoot, ".nojekyll"), "");

  let pageCount = 0;
  for (const language of LANGUAGES) {
    const sourceDir = path.join(contentRoot, language.dir);
    const sources = Object.fromEntries(PAGES.map((page) => {
      const file = path.join(sourceDir, `${page}.md`);
      if (!fs.existsSync(file)) throw new Error(`missing page: ${path.relative(repo, file)}`);
      return [page, fs.readFileSync(file, "utf8")];
    }));
    const titles = Object.fromEntries(PAGES.map((page) => [page, pageTitle(sources[page], page)]));
    const targetDir = path.join(outRoot, language.dir);
    fs.mkdirSync(targetDir, { recursive: true });
    const { markdown: toolsPage, placements } = placeTools(sources.tools, language.code);
    sources.tools = toolsPage;
    for (const page of PAGES) {
      const { html, outline } = renderMarkdown(sources[page], language.code);
      fs.writeFileSync(
        path.join(targetDir, `${page}.html`),
        layout({ lang: language.code, page, title: titles[page], html, outline, titles })
      );
      pageCount += 1;
    }

    // One page per catalog tool. The notes file is required in both languages
    // so a tool cannot be documented in one and silently missing in the other.
    const toolsDir = path.join(targetDir, "tools");
    fs.mkdirSync(toolsDir, { recursive: true });
    for (const tool of baseline.catalog[language.code]) {
      const notesFile = path.join(sourceDir, "tools", `${tool.name}.md`);
      if (!fs.existsSync(notesFile)) throw new Error(`missing tool notes: ${path.relative(repo, notesFile)}`);
      const { html, outline, title } = renderToolPage(language.code, tool, fs.readFileSync(notesFile, "utf8"), placements.get(tool.name));
      fs.writeFileSync(
        path.join(toolsDir, `${tool.name}.html`),
        layout({ lang: language.code, page: "tools", slug: `tools/${tool.name}`, title, html, outline, titles, depth: 1 })
      );
      pageCount += 1;
    }
    const orphanNotes = fs.existsSync(path.join(sourceDir, "tools"))
      ? fs.readdirSync(path.join(sourceDir, "tools")).filter((entry) => entry.endsWith(".md") && !baseline.catalog.en.some((tool) => `${tool.name}.md` === entry))
      : [];
    if (orphanNotes.length) throw new Error(`tool notes without a catalog tool: ${orphanNotes.join(", ")}`);
  }

  // The root page picks the reader's language once, then remembers nothing:
  // every page carries explicit language links. It is also the only place on the
  // site with room for the full icon — the header chip and the favicon are both
  // small enough that they take the mark-only asset instead.
  fs.writeFileSync(path.join(outRoot, "index.html"), `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Mework docs</title>
<link rel="stylesheet" href="assets/style.css">
<link rel="icon" href="assets/mework-icon-small.svg" type="image/svg+xml">
<script>
(function () {
  var zh = /^zh/i.test(navigator.language || "");
  location.replace((zh ? "zh-CN" : "en") + "/index.html");
})();
</script>
</head>
<body>
<main class="content landing">
<p><img src="assets/mework-icon.svg" alt="" width="96" height="96" style="border-radius:22px"></p>
<h1>Mework docs</h1>
<p><a href="en/index.html">English</a> · <a href="zh-CN/index.html">简体中文</a></p>
</main>
</body>
</html>
`);
  console.log(`built ${pageCount} pages into ${path.relative(repo, outRoot)}`);
}

build();
