//! Host-resolved managed/user instruction-file roots for the project-memory
//! loader. Roots come from fixed host locations, never from renderer input.

use crate::project_memory::ProjectMemoryOptions;
use std::path::PathBuf;

#[derive(Clone)]
pub(crate) struct MemoryLocationRoots {
    managed_mework: PathBuf,
    home: Option<PathBuf>,
}

impl MemoryLocationRoots {
    pub(crate) fn for_host() -> Self {
        Self {
            managed_mework: managed_instruction_path(),
            home: dirs::home_dir(),
        }
    }

    /// Every project-memory discovery entry point applies its roots through
    /// this one resolver, so the managed/user locations the runtime reads
    /// cannot diverge between call sites.
    pub(crate) fn apply_to_project_memory_options(&self, options: &mut ProjectMemoryOptions) {
        options.managed_mework_policy_file = Some(self.managed_mework.clone());
        options.trusted_user_home = self.home.clone();
    }
}

#[cfg(target_os = "windows")]
fn managed_instruction_path() -> PathBuf {
    use std::os::windows::ffi::OsStringExt as _;
    use windows_sys::Win32::UI::Shell::{
        SHGetFolderPathW, CSIDL_PROGRAM_FILES, SHGFP_TYPE_CURRENT,
    };

    // Managed policy authority must not come from a mutable process
    // environment variable. Resolve Windows' Program Files known folder
    // directly; keep the literal only as a fail-closed platform fallback.
    let mut buffer = [0_u16; 260];
    let result = unsafe {
        SHGetFolderPathW(
            std::ptr::null_mut(),
            CSIDL_PROGRAM_FILES as i32,
            std::ptr::null_mut(),
            SHGFP_TYPE_CURRENT as u32,
            buffer.as_mut_ptr(),
        )
    };
    let program_files = if result >= 0 {
        let length = buffer
            .iter()
            .position(|value| *value == 0)
            .unwrap_or(buffer.len());
        let resolved = std::ffi::OsString::from_wide(&buffer[..length]);
        if resolved.is_empty() {
            PathBuf::from(r"C:\Program Files")
        } else {
            PathBuf::from(resolved)
        }
    } else {
        PathBuf::from(r"C:\Program Files")
    };
    program_files.join("Mework").join("MEWORK.md")
}

#[cfg(target_os = "macos")]
fn managed_instruction_path() -> PathBuf {
    PathBuf::from("/Library/Application Support")
        .join("Mework")
        .join("MEWORK.md")
}

#[cfg(all(unix, not(target_os = "macos")))]
fn managed_instruction_path() -> PathBuf {
    PathBuf::from("/etc/mework/MEWORK.md")
}

#[cfg(test)]
mod tests {
    #[test]
    fn invoke_browser_bridge_and_acl_are_all_wired() {
        // Registration lives in four places and a command silently fails if any
        // one is missed, so each new memory command is checked in all of them.
        for command in [
            "mework_memory_overview",
            "mework_memory_read_file",
            "mework_memory_write_file",
            "mework_memory_delete_document",
        ] {
            assert!(include_str!("../app_commands.rs").contains(command), "{command}");
            assert!(
                include_str!("browser_dev.rs").contains(&format!("\"{command}\"")),
                "{command}"
            );
            assert!(
                include_str!("../capabilities/default.json")
                    .contains(&format!("\"allow-{}\"", command.replace('_', "-"))),
                "{command}"
            );
        }
        for (command, toml) in [
            (
                "mework_memory_overview",
                include_str!("../permissions/autogenerated/mework_memory_overview.toml"),
            ),
            (
                "mework_memory_read_file",
                include_str!("../permissions/autogenerated/mework_memory_read_file.toml"),
            ),
            (
                "mework_memory_write_file",
                include_str!("../permissions/autogenerated/mework_memory_write_file.toml"),
            ),
            (
                "mework_memory_delete_document",
                include_str!("../permissions/autogenerated/mework_memory_delete_document.toml"),
            ),
        ] {
            assert!(
                toml.contains(&format!("commands.allow = [\"{command}\"]")),
                "{command}"
            );
        }

        // The retired model-owned memory commands must stay gone. If one comes
        // back it would reintroduce the per-model namespace this design removed.
        for retired in [
            "memory_snapshot",
            "memory_list_model_ids",
            "memory_list_documents",
            "memory_list_revisions",
            "memory_restore_revision",
            "memory_purge_quarantine",
            "memory_export_namespace",
            "memory_rebind_namespace",
        ] {
            assert!(
                !include_str!("../app_commands.rs").contains(retired),
                "{retired} must not be registered"
            );
        }
    }
}
